### ISSUE TITLE
I cannot download en-es.5000-6500.txt

### ISSUE THREAD

**Issue by veer66** [facebookresearch/Non-adversarialTranslation#1]
By running, sh download.sh, I cannot download https://s3.amazonaws.com/arrival/dictionaries/en-es.5000-6500.txt

![default](https://user-images.githubusercontent.com/370688/52615247-24116480-2ec7-11e9-8901-ad97d7e6a84b.png)

**Comment by Yedid** [comment]
Thanks for letting me know, links updated.
